import React, { useState } from 'react';
import { View, StyleSheet, ScrollView, TextInput, Pressable, Alert } from 'react-native';
import { ChevronDown, ChevronUp, FileCode } from 'lucide-react-native';
import { Screen as AtomicScreen } from '@/src/components/atoms/Screen';
import { ScreenHeader } from '@/src/components/molecules/ScreenHeader';
import { ThemedText } from '@/src/components/atoms/ThemedText';
import { Button } from '@/src/components/atoms/Button';
import { useThemeTokens } from '@/src/hooks/useThemeTokens';

const EXPORT_ITEMS = [
	{ key: 'sales', label: 'Sales Vouchers', defaultOn: true },
	{ key: 'purchases', label: 'Purchase Vouchers', defaultOn: true },
	{ key: 'payments', label: 'Payment Vouchers', defaultOn: true },
	{ key: 'receipts', label: 'Receipt Vouchers', defaultOn: true },
	{ key: 'parties', label: 'Party Master', defaultOn: true },
	{ key: 'items', label: 'Item Master', defaultOn: false },
];

const INSTRUCTIONS = [
	'Open TallyPrime on your computer',
	'Go to: Gateway of Tally → Import Data → Vouchers',
	'Select the XML file generated by this app',
	'Verify imported data in Tally',
	'Contact your CA if any entries need adjustment',
];

interface ChipProps {
	label: string;
	active: boolean;
	onPress: () => void;
	colors: any;
	borderRadius: any;
}

const Chip = ({ label, active, onPress, colors, borderRadius }: ChipProps) => (
	<Pressable
		onPress={onPress}
		style={[
			styles.chip,
			{
				borderColor: active ? colors.primary : colors.border,
				backgroundColor: active ? colors.primary : colors.surface,
				borderRadius: borderRadius.full,
			},
		]}
	>
		<ThemedText variant="caption" color={active ? '#FFF' : colors.onSurface}>
			{label}
		</ThemedText>
	</Pressable>
);

export default function TallyExportScreen() {
	const { c, s, r } = useThemeTokens();
	const [period, setPeriod] = useState<'month' | 'fy' | 'custom'>('fy');
	const [tallyVersion, setTallyVersion] = useState<'prime' | 'erp9'>('prime');
	const [selected, setSelected] = useState<Record<string, boolean>>(
		Object.fromEntries(EXPORT_ITEMS.map((i) => [i.key, i.defaultOn])),
	);
	const [salesAccount, setSalesAccount] = useState('Sales Account');
	const [purchaseAccount, setPurchaseAccount] = useState('Purchase Account');
	const [cashAccount, setCashAccount] = useState('Cash');
	const [showInstructions, setShowInstructions] = useState(false);

	const toggle = (key: string) => setSelected((prev) => ({ ...prev, [key]: !prev[key] }));

	const handleExport = () => {
		const selectedItems = EXPORT_ITEMS.filter((i) => selected[i.key])
			.map((i) => i.label)
			.join(', ');
		const filename = `TallyData_${period === 'month' ? 'Apr2025' : '2024-25'}.xml`;
		Alert.alert(
			'Export Ready',
			`${filename} generated with: ${selectedItems}.\n\nShare this file with your CA or import directly into TallyPrime.`,
			[
				{
					text: 'Share',
					onPress: () => Alert.alert('Share', 'Native share sheet coming soon'),
				},
				{ text: 'OK' },
			],
		);
	};

	return (
		<AtomicScreen withKeyboard safeAreaEdges={['bottom']}>
			<ScreenHeader title="Export to Tally" />
			<ScrollView
				contentContainerStyle={{ padding: s.lg, paddingBottom: 32 }}
				keyboardShouldPersistTaps="handled"
			>
				<View
					style={[
						styles.infoCard,
						{ backgroundColor: c.primary + '15', borderRadius: r.lg },
					]}
				>
					<FileCode size={24} color={c.primary} style={{ marginBottom: s.sm }} />
					<ThemedText variant="bodyBold" color={c.primary}>
						Export your data to TallyPrime or Tally ERP 9
					</ThemedText>
					<ThemedText
						variant="caption"
						color={c.onSurfaceVariant}
						style={{ marginTop: 4 }}
					>
						Generates a .xml file you can share with your CA or import directly into
						Tally.
					</ThemedText>
				</View>

				<ThemedText variant="h3" style={styles.sectionHeader}>
					Period
				</ThemedText>
				<View style={styles.chipRow}>
					<Chip
						label="Current Month"
						active={period === 'month'}
						onPress={() => setPeriod('month')}
						colors={c}
						borderRadius={r}
					/>
					<Chip
						label="Current FY (2024-25)"
						active={period === 'fy'}
						onPress={() => setPeriod('fy')}
						colors={c}
						borderRadius={r}
					/>
					<Chip
						label="Custom"
						active={period === 'custom'}
						onPress={() => setPeriod('custom')}
						colors={c}
						borderRadius={r}
					/>
				</View>

				<ThemedText variant="h3" style={styles.sectionHeader}>
					Tally Version
				</ThemedText>
				<View style={styles.chipRow}>
					<Chip
						label="TallyPrime"
						active={tallyVersion === 'prime'}
						onPress={() => setTallyVersion('prime')}
						colors={c}
						borderRadius={r}
					/>
					<Chip
						label="Tally ERP 9"
						active={tallyVersion === 'erp9'}
						onPress={() => setTallyVersion('erp9')}
						colors={c}
						borderRadius={r}
					/>
				</View>

				<ThemedText variant="h3" style={styles.sectionHeader}>
					What to Export
				</ThemedText>
				<View style={[styles.checkList, { borderColor: c.border, borderRadius: r.lg }]}>
					{EXPORT_ITEMS.map((item, i) => (
						<Pressable
							key={item.key}
							onPress={() => toggle(item.key)}
							style={[
								styles.checkRow,
								{
									borderBottomColor: c.border,
									borderBottomWidth:
										i < EXPORT_ITEMS.length - 1 ? StyleSheet.hairlineWidth : 0,
								},
							]}
						>
							<View
								style={[
									styles.checkbox,
									{
										borderColor: selected[item.key] ? c.primary : c.border,
										backgroundColor: selected[item.key]
											? c.primary
											: 'transparent',
										borderRadius: r.sm,
									},
								]}
							>
								{selected[item.key] && (
									<ThemedText
										variant="caption"
										color="#FFF"
										style={styles.checkMark}
									>
										✓
									</ThemedText>
								)}
							</View>
							<ThemedText variant="body">{item.label}</ThemedText>
						</Pressable>
					))}
				</View>

				<ThemedText variant="h3" style={styles.sectionHeader}>
					Ledger Mapping
				</ThemedText>
				<ThemedText
					variant="caption"
					color={c.onSurfaceVariant}
					style={{ marginBottom: s.md }}
				>
					Enter the ledger names as they appear in Tally
				</ThemedText>
				{[
					{ label: 'Sales Account', value: salesAccount, setter: setSalesAccount },
					{
						label: 'Purchase Account',
						value: purchaseAccount,
						setter: setPurchaseAccount,
					},
					{ label: 'Cash Account', value: cashAccount, setter: setCashAccount },
				].map(({ label, value, setter }) => (
					<View key={label} style={{ marginBottom: s.sm }}>
						<ThemedText
							variant="label"
							color={c.onSurfaceVariant}
							style={{ marginBottom: 4 }}
						>
							{label}
						</ThemedText>
						<TextInput
							value={value}
							onChangeText={setter}
							style={[
								styles.input,
								{ borderColor: c.border, color: c.onSurface, borderRadius: r.md },
							]}
						/>
					</View>
				))}

				<Button
					title="Generate XML File"
					onPress={handleExport}
					style={{ marginTop: s.lg }}
				/>

				{/* Collapsible instructions */}
				<Pressable
					onPress={() => setShowInstructions(!showInstructions)}
					style={[
						styles.instructionsHeader,
						{ borderColor: c.border, borderRadius: r.md, marginTop: s.lg },
					]}
				>
					<ThemedText variant="bodyBold">How to import in TallyPrime</ThemedText>
					{showInstructions ? (
						<ChevronUp size={18} color={c.onSurfaceVariant} />
					) : (
						<ChevronDown size={18} color={c.onSurfaceVariant} />
					)}
				</Pressable>
				{showInstructions && (
					<View
						style={[
							styles.instructionsList,
							{ borderColor: c.border, borderRadius: r.md },
						]}
					>
						{INSTRUCTIONS.map((step, i) => (
							<View
								key={i}
								style={[
									styles.instructionRow,
									{
										borderBottomColor: c.border,
										borderBottomWidth:
											i < INSTRUCTIONS.length - 1
												? StyleSheet.hairlineWidth
												: 0,
									},
								]}
							>
								<View style={[styles.stepNum, { backgroundColor: c.primary }]}>
									<ThemedText variant="caption" color="#FFF">
										{i + 1}
									</ThemedText>
								</View>
								<ThemedText variant="body" style={{ flex: 1 }}>
									{step}
								</ThemedText>
							</View>
						))}
					</View>
				)}
			</ScrollView>
		</AtomicScreen>
	);
}

const styles = StyleSheet.create({
	infoCard: { padding: 16, marginBottom: 8 },
	sectionHeader: { marginTop: 20, marginBottom: 10 },
	chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 4 },
	chip: { paddingHorizontal: 14, paddingVertical: 8, borderWidth: 1 },
	checkList: { borderWidth: 1, overflow: 'hidden' },
	checkRow: { flexDirection: 'row', alignItems: 'center', padding: 14, gap: 12 },
	checkbox: {
		width: 22,
		height: 22,
		borderWidth: 2,
		alignItems: 'center',
		justifyContent: 'center',
	},
	checkMark: { lineHeight: 16 },
	input: { borderWidth: 1, padding: 12, fontSize: 16 },
	instructionsHeader: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		padding: 14,
		borderWidth: 1,
	},
	instructionsList: { borderWidth: 1, borderTopWidth: 0, overflow: 'hidden' },
	instructionRow: { flexDirection: 'row', alignItems: 'center', padding: 14, gap: 12 },
	stepNum: {
		width: 24,
		height: 24,
		borderRadius: 12,
		alignItems: 'center',
		justifyContent: 'center',
	},
});
